# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "07dv0lx6cbcjz8dhld2x1lls1v155ip5jsswnyaqws0hh479lm6k";
    x86_64-linux = "1i52a9p1158sb75qlmj6y0z79idy5m0gwfipvv9ibxih7d965r27";
    armv6l-linux = "0irm2617scgzw77a61jp2g6fvdms42nlkbazcf4hgvmbb6br1vc3";
    aarch64-linux = "16glh2rqxwl1pbxgvhc6jkj7mpvw5byl7s6bv1w98cgbwns8ql7c";
    x86_64-darwin = "1gx9iraw1qly90wx52dgzymclbydyg8k52cl2pd0cj5p008lz1xl";
    aarch64-darwin = "1gx9iraw1qly90wx52dgzymclbydyg8k52cl2pd0cj5p008lz1xl";
  };

  urlMap = {
    i686-linux = "https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.10-pre17/clilol_1.0.10-pre17_linux_386.tar.gz";
    x86_64-linux = "https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.10-pre17/clilol_1.0.10-pre17_linux_amd64.tar.gz";
    armv6l-linux = "https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.10-pre17/clilol_1.0.10-pre17_linux_armv6.tar.gz";
    aarch64-linux = "https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.10-pre17/clilol_1.0.10-pre17_linux_arm64.tar.gz";
    x86_64-darwin = "https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.10-pre17/clilol_1.0.10-pre17_darwin_all.tar.gz";
    aarch64-darwin = "https://git.mcornick.dev/mcornick/clilol/releases/download/v1.0.10-pre17/clilol_1.0.10-pre17_darwin_all.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "clilol";
  version = "1.0.10-pre17";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clilol $out/bin/clilol
    installManPage ./manpages/*.1
  '';
  postInstall = ''
    installShellCompletion ./completions/*.1
  '';

  system = system;

  meta = {
    description = "A CLI for omg.lol";
    homepage = "https://clilol.readthedocs.io/";
    license = lib.licenses.mpl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
