# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "0jzmwqvkhamaxvkaks1i0lxkisny4bkcz7gi86s5vp1bnsp040zl";
    x86_64-linux = "0f6wxjihgbww0ni1igf852j5r4if67h7y4f7i8n3mh7a24sf3gwj";
    armv6l-linux = "0n2nzp3qh3h02bf6lrh032yc5g1ywsj1g1r1msz0bb71fywn7704";
    aarch64-linux = "0329b904vkpcyi6yns9w669r6gbrrsjhvzmnmq5r43wmmsm1rxbi";
    x86_64-darwin = "0lwxcsix3sd0xsc5rlsdxhzkczijp53qlgzr7xpkg8gxlrbg741r";
    aarch64-darwin = "0lwxcsix3sd0xsc5rlsdxhzkczijp53qlgzr7xpkg8gxlrbg741r";
  };

  urlMap = {
    i686-linux = "https://github.com/mcornick/clilol/releases/download/v1.0.18-pre1/clilol_1.0.18-pre1_linux_386.tar.gz";
    x86_64-linux = "https://github.com/mcornick/clilol/releases/download/v1.0.18-pre1/clilol_1.0.18-pre1_linux_amd64.tar.gz";
    armv6l-linux = "https://github.com/mcornick/clilol/releases/download/v1.0.18-pre1/clilol_1.0.18-pre1_linux_armv6.tar.gz";
    aarch64-linux = "https://github.com/mcornick/clilol/releases/download/v1.0.18-pre1/clilol_1.0.18-pre1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/mcornick/clilol/releases/download/v1.0.18-pre1/clilol_1.0.18-pre1_darwin_all.tar.gz";
    aarch64-darwin = "https://github.com/mcornick/clilol/releases/download/v1.0.18-pre1/clilol_1.0.18-pre1_darwin_all.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "clilol";
  version = "1.0.18-pre1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./clilol $out/bin/clilol
    installManPage ./manpages/*.1
    installShellCompletion ./completions/clilol.{bash,fish,zsh}
  '';

  system = system;

  meta = {
    description = "A CLI for omg.lol";
    homepage = "https://clilol.readthedocs.io/";
    license = lib.licenses.mpl20;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv6l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
